"""初始数据库结构

Revision ID: 923ce7a35c59
Revises: 
Create Date: 2026-01-03 12:52:55.059919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923ce7a35c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'TECHNICAL', 'TROUBLESHOOTING', 'SECURITY', 'CASE_STUDY', name='qacategory'), nullable=False, comment='知識領域'),
    sa.Column('analysis_period_start', sa.DateTime(), nullable=False, comment='分析開始時間'),
    sa.Column('analysis_period_end', sa.DateTime(), nullable=False, comment='分析結束時間'),
    sa.Column('common_issues', sa.JSON(), nullable=True, comment='常見問題（JSON格式）'),
    sa.Column('optimization_suggestions', sa.JSON(), nullable=True, comment='優化建議（JSON格式）'),
    sa.Column('statistics', sa.JSON(), nullable=True, comment='統計數據（JSON格式）'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False, comment='分析時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_analysis_category'), 'feedback_analysis', ['category'], unique=False)
    op.create_index(op.f('ix_feedback_analysis_id'), 'feedback_analysis', ['id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'TECHNICAL', 'TROUBLESHOOTING', 'SECURITY', 'CASE_STUDY', name='qacategory'), nullable=False, comment='知識領域'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='模板名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('template_content', sa.Text(), nullable=False, comment='模板內容'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本號'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='模板參數配置'),
    sa.Column('optimization_history', sa.JSON(), nullable=True, comment='優化歷史記錄'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_is_active'), 'prompt_templates', ['is_active'], unique=False)
    op.create_table('qa_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False, comment='問題文本'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案文本'),
    sa.Column('category', sa.Enum('GENERAL', 'TECHNICAL', 'TROUBLESHOOTING', 'SECURITY', 'CASE_STUDY', name='qacategory'), nullable=False, comment='知識領域'),
    sa.Column('status', sa.Enum('GENERATING', 'PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'REJECTED', 'MODIFIED', name='qastatus'), nullable=True, comment='狀態'),
    sa.Column('generator_score', sa.Integer(), nullable=True, comment='生成模組評分 (0-100)'),
    sa.Column('reviewer_score', sa.Integer(), nullable=True, comment='審查模組評分 (0-100)'),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True, comment='使用的提示詞模板ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新時間'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='審查時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_pairs_category'), 'qa_pairs', ['category'], unique=False)
    op.create_index(op.f('ix_qa_pairs_id'), 'qa_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_qa_pairs_status'), 'qa_pairs', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_pair_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True, comment='審查人ID'),
    sa.Column('action', sa.Enum('APPROVE', 'MODIFY', 'REJECT', name='reviewaction'), nullable=False, comment='操作類型'),
    sa.Column('modified_question', sa.Text(), nullable=True, comment='修改後的問題'),
    sa.Column('modified_answer', sa.Text(), nullable=True, comment='修改後的答案'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='反饋意見'),
    sa.Column('review_reason', sa.Text(), nullable=True, comment='審查原因'),
    sa.Column('feedback_categories', sa.JSON(), nullable=True, comment='反饋分類列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='創建時間'),
    sa.ForeignKeyConstraint(['qa_pair_id'], ['qa_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_qa_pair_id'), 'reviews', ['qa_pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_qa_pair_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_qa_pairs_status'), table_name='qa_pairs')
    op.drop_index(op.f('ix_qa_pairs_id'), table_name='qa_pairs')
    op.drop_index(op.f('ix_qa_pairs_category'), table_name='qa_pairs')
    op.drop_table('qa_pairs')
    op.drop_index(op.f('ix_prompt_templates_is_active'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_feedback_analysis_id'), table_name='feedback_analysis')
    op.drop_index(op.f('ix_feedback_analysis_category'), table_name='feedback_analysis')
    op.drop_table('feedback_analysis')
    # ### end Alembic commands ###

